language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - cd BCCVL_Visualiser
  - pip install setuptools --upgrade
  - python bootstrap.py -c buildout.cfg
  - bin/buildout -N -t 3 -c buildout.cfg
# command to run tests
script:
  - cd BCCVL_Visualiser
  - python setup.py test
