language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install build-essential python-gdal libcurl4-gnutls-dev libpng12-dev libgd2-xpm-dev libgif-dev libjpeg-dev libblas-dev libsuitesparse-dev libatlas-base-dev liblapack-dev swig gfortran python-mapscript libgdal-dev proj
  - cd BCCVL_Visualiser
  - pip install setuptools --upgrade
  # Use the packages instead of the buildout for travis
  - python bootstrap.py -c travis_buildout.cfg
  - bin/buildout -N -t 3 -c travis_buildout.cfg
# command to run tests
script:
  - bin/test
