language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install build-essential libcurl4-gnutls-dev libpng12-dev libgd2-xpm-dev libgif-dev libjpeg-dev libblas-dev libatlas-base-dev liblapack-dev gfortran
  - cd BCCVL_Visualiser
  - pip install setuptools --upgrade
  - python bootstrap.py -c buildout.cfg
  - bin/buildout -N -t 3 -c buildout.cfg
# command to run tests
script:
  - cd BCCVL_Visualiser
  - python setup.py test
