language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
# command to install dependencies
env:
  - PACKAGES=true
install:
  - sudo apt-add-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install build-essential libcurl4-gnutls-dev libpng12-dev libgd2-xpm-dev libgif-dev libjpeg-dev libblas-dev libsuitesparse-dev libatlas-base-dev liblapack-dev swig gfortran libgdal-dev proj libproj-dev libgeos-dev
  - cd BCCVL_Visualiser
  - pip freeze
  - pip install setuptools --upgrade
  - python bootstrap.py -c buildout.cfg
  - bin/buildout -t 30 -c buildout.cfg
  - pip freeze
# command to run tests
script:
  - bin/test
